### ISSUE TITLE
Add PDF with prefilled information for Spam lawsuit

### ISSUE THREAD

**Issue by oferb** [hasadna/monorepo#56]
Here is an example template for a lawsuit document:
https://www.isoc.org.il/wp-content/uploads/2016/02/template_process.rtf

We'd like to create a PDF that is prefilled with all the information.
Some of the information will come from the backend, regarding the SMS, sender etc.
The rest will come from the user.

With this PDF, the user can file a lawsuit against the Spam sender in a "small lawsuit court" (tviot ktanot).

The app is here:
https://github.com/hasadna/hasadna/tree/master/projects/noloan2
Note: There is an older version built with Bazel here, that we are copying parts into the above, and will eventually delete:
https://github.com/hasadna/hasadna/tree/master/projects/noloan

Let's break this task into parts:
1. Find a suitable library (perhaps https://www.blueappsoftware.com/how-to-create-pdf-file-in-android/) that can print PDFs in Hebrew.
2. Add an activity to get the required information from the user.
3. Create PDF that the user can share (e.g send to email etc).

If there's any question, please ask!

**Comment by cotom972** [comment]
Done.
